# Usar uma imagem base do PostgreSQL
FROM postgres:15

# Variáveis de ambiente para o banco de dados
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin
ENV POSTGRES_DB=mydatabase

# Expor a porta padrão do PostgreSQL
EXPOSE 5432
