version: '3.9'

services:
  postgres:
    build: .
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gustavo
      POSTGRES_PASSWORD: j026jY)O2<s
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: gustavo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: j026jY)O2<s
    depends_on:
      - postgres

volumes:
  postgres_data:
